### PR TITLE
Allow disabling of request or ActiveRecord datasets

### LINKED ISSUE #5: Consider adding a way to configure toggling off ActiveRecord events
If people use some other method to send DB-related events or want to limit their event volume, it may be nice to have a way to continue to send rails request events but disable sending ActiveRecord events. e.g.

```ruby
HoneycombRails.configure do |conf|
  conf.writekey = 'your honeycomb writekey here'
  conf.dataset = 'your app name'
  conf.send_db_events = false
end
```

### PR DESCRIPTION
**Pull request by christineyen**
Fixes #5 . (Feedback re: relying on empty-string-equality, or suggestions for tests around this are v. welcome.)

Also happy to log out somewhere to complain if **no** subscribers are defined as a result.

### CODE REVIEW

**Review by eanakashima — APPROVED** [review]
Nice.

> Also happy to log out somewhere to complain if no subscribers are defined as a result.

Good idea. Any opinion on how you'd want to let people turn off/redirect logs? Maybe we let people pass in a logger and fall back to Rails logger as the default? (Not that this decision blocks adding logging, or that adding that log message should block this PR, just thinking out loud.)

**Comment by christineyen** [comment]
Hrmmmm.

> Maybe we let people pass in a logger and fall back to Rails logger as the default?

For outputting that message, or for toggling subscriber existence? For the former, I don't feel strongly; whichever is more conventional Rails-y. If the latter (which I don't think you mean), I'd argue that making a `libhoney` logger and Rails logger have a similar interface isn't worth it.

Pushed a change to support the former (defaulting to `Rails.logger` to log a warning if no subscribers are populated), happy to have the approach overridden with something more canonical in the future :)

**Comment by samstokes** [comment]
Thanks for adding this! Out of interest, what was the use case? Did somebody hit #3 and go wtf?

**Comment by christineyen** [comment]
I wanted to be able to offer Rails request instrumentation without ActiveRecord, and/or vice versa, and it felt unfortunate that the gem forcibly couples the two.

**Pull request merged**
